inherits = "everforest-dark-medium"

[palette]

# background light medium

bg_dim = "#EFEBD4"
bg0 = "#FDF6E3"
bg1 = "#F4F0D9"
bg2 = "#EFEBD4"
bg3 = "#E6E2CC"
bg4 = "#E0DCC7"
bg5 = "#BDC3AF"
bg_visual = "#EAEDC8"
bg_red = "#FBE3DA"
bg_green = "#F0F1D2"
bg_blue = "#E9F0E9"
bg_yellow = "#FAEDCD"

# foreground light

fg = "#5C6A72"
red = "#F85552"
orange = "#F57D26"
yellow = "#DFA000"
green = "#8DA101"
aqua = "#35A77C"
blue = "#3A94C5"
purple = "#DF69BA"

grey0 = "#A6B0A0"
grey1 = "#939F91"
grey2 = "#829181"

statusline1 = "#93B259"
statusline2 = "#708089"
statusline3 = "#E66868"
