inherits = "everforest-dark-medium"

[palette]

# background dark hard

"bg_dim" = "#1e2326"
"bg0" = "#272e33"
"bg1" = "#2e383c"
"bg2" = "#374145"
"bg3" = "#414b50"
"bg4" = "#495156"
"bg5" = "#4f5b58"
"bg_visual" = "#4c3743"
"bg_red" = "#493b40"
"bg_green" = "#3c4841"
"bg_blue" = "#384b55"
"bg_yellow" = "#45443c"
