inherits = "everforest-light-medium"

[palette]

# background light hard

"bg_dim" = "#f2efdf"
"bg0" = "#fffbef"
"bg1" = "#f8f5e4"
"bg2" = "#f2efdf"
"bg3" = "#edeada"
"bg4" = "#e8e5d5"
"bg5" = "#bec5b2"
"bg_visual" = "#f0f2d4"
"bg_red" = "#ffe7de"
"bg_green" = "#f3f5d9"
"bg_blue" = "#ecf5ed"
"bg_yellow" = "#fef2d5"
